---
title: "Case Study 12"
author: Tina Ni 
date: November 19, 2024
output: github_document
---
```{r Install Packages}
# install.packages("openmeteo")
# install.packages("htmlwidgets")
# install.packages("widgetframe")
# install.packages("xts")
# install.packages("dygraphs")
library(openmeteo)
library(tidyverse)
library(htmlwidgets)
library(widgetframe)
library(xts)
library(dygraphs)
```
```{r}
temp_df<- weather_history(c(43.00923265935055, -78.78494250958327),start = "2023-01-01",end=today(),
                  daily=list("temperature_2m_max","temperature_2m_min","precipitation_sum")) %>% 
  mutate(daily_temperature_2m_mean=(daily_temperature_2m_max+daily_temperature_2m_min)/2)

temp <- select(temp_df, daily_temperature_2m_min,daily_temperature_2m_mean,daily_temperature_2m_max) %>% 
        xts(order.by = temp_df$date, frequency(365))

dygraph(temp, main = "Daily Maximum Temperature in Buffalo, NY") %>%
dySeries("daily_temperature_2m_mean", label = "Mean") %>%
  dySeries("daily_temperature_2m_max", label = "Max") %>%
  dySeries("daily_temperature_2m_min", label = "Min") %>%
  dyAxis("y", label = "Temperature (C)", valueRange = c(-20, 40))%>%
  dyAxis("x",label = "Date", drawGrid = FALSE)%>%
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE)%>%
  dyRangeSelector(dateWindow = c("2023-01-01", "2024-11-17"))
```


