---
title: "Case Study 09"
author: Tina Ni
date: October 29, 2024
output: github_document
---

```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(spData)
data(world)
data(us_states)

dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/ibtracs.NA.list.v04r01.csv"

storm_data <- read_csv(dataurl)
```

```{r}

storms <- storm_data %>%
  mutate (YEAR = year(ISO_TIME)) %>%
  filter (YEAR >= 1950 ) %>%
  mutate_if (is.numeric, function(x) ifelse (x == -999.0, NA, x)) %>%
  mutate (DECADE = (floor (YEAR/10) * 10)) %>%
  st_as_sf (coords = c("LON","LAT"),crs = 4326)

region <- st_bbox(storms)

ggplot(data = world)+
  
stat_bin2d(data=storms, aes(y = st_coordinates(storms)[,2], x = st_coordinates(storms)[,1]), bins = 100) +
##stat_bin2d puts in the next data
  
scale_fill_distiller(palette = "YlOrRd", trans = "log", direction = -1, breaks = c(1,10,100,1000)) + 
  
coord_sf(ylim = region [c(2,4)], xlim = region[c(1,3)]) + 
geom_sf()+
facet_wrap(~DECADE)

## -137 longitude

```


```{r}
crs2<- st_crs(storms)
US <- st_transform(us_states, crs = crs2)
US <- US %>%
  select (state = NAME)
storm_states <- st_join(storms, US, join = st_intersects,left = F)

new_storm_states <- storm_states %>%
  group_by(state) %>%
  summarize(storms=length(unique(NAME)))%>%
  arrange(desc(storms)) %>%
  select(state, storms) %>%
  slice(1:5)

print(new_storm_states)
  
```