---
title: "Case Study 10"
author: Tina Ni
date: November 6, 2024
output: github_document
---

```{r}
library (terra)
library (rasterVis)
library (ggmap)
library (knitr)
library (sf)
library (ncdf4)
library (dplyr)
library (stringr)
library (raster)
library (tidyverse)
```

```{r}
# Create afolder to hold the downloaded data
dir.create("data",showWarnings = F) #create a folder to hold the data

lulc_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MCD12Q1.051_aid0001.nc?raw=true"
lst_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MOD11A2.006_aid0001.nc?raw=true"

# download them
download.file(lulc_url,destfile="data/MCD12Q1.051_aid0001.nc", mode="wb")
download.file(lst_url,destfile="data/MOD11A2.006_aid0001.nc", mode="wb")
```

```{r}
lulc=rast("data/MCD12Q1.051_aid0001.nc",subds="Land_Cover_Type_1")
lst=rast("data/MOD11A2.006_aid0001.nc",subds="LST_Day_1km")
```

```{r}
lulc = lulc[[13]]
plot(lulc)
```

```{r}
#Process land cover data, Assigning land cover classes from MODIS Website
Land_Cover_Type_1 = c(
    Water = 0, 
    `Evergreen Needleleaf forest` = 1, 
    `Evergreen Broadleaf forest` = 2,
    `Deciduous Needleleaf forest` = 3, 
    `Deciduous Broadleaf forest` = 4,
    `Mixed forest` = 5, 
    `Closed shrublands` = 6,
    `Open shrublands` = 7,
    `Woody savannas` = 8, 
    Savannas = 9,
    Grasslands = 10,
    `Permanent wetlands` = 11, 
    Croplands = 12,
    `Urban & built-up` = 13,
    `Cropland/Natural vegetation mosaic` = 14, 
    `Snow & ice` = 15,
    `Barren/Sparsely vegetated` = 16, 
    Unclassified = 254,
    NoDataFill = 255)

land_cover_data=data.frame(
  ID=Land_Cover_Type_1,
  landcover=names(Land_Cover_Type_1),
  col=c("#000080","#008000","#00FF00", "#99CC00","#99FF99", "#339966", "#993366", "#FFCC99", 
        "#CCFFCC", "#FFCC00", "#FF9900", "#006699", "#FFFF00", "#FF0000", "#999966", "#FFFFFF", 
        "#808080", "#000000", "#000000"),
  stringsAsFactors = F)
# colors from https://lpdaac.usgs.gov/about/news_archive/modisterra_land_cover_types_yearly_l3_global_005deg_cmg_mod12c1
kable(head(land_cover_data))
```

```{r}
# Convert LULC raster into a ‘factor’ (categorical) raster.
# This requires building the Raster Attribute Table (RAT)
#convert to raster (easy)
lulc=as.factor(lulc)

# update the RAT with a left join
levels(lulc)=left_join(levels(lulc)[[1]],land_cover_data)[-1,]
activeCat(lulc)=1

# plot it
gplot(lulc)+
  geom_raster(aes(fill=as.factor(value)))+
  scale_fill_manual(values=setNames(land_cover_data$col,land_cover_data$ID),
                    labels=land_cover_data$landcover,
                    breaks=land_cover_data$ID,
                    name="Landcover Type")+
  coord_equal()+
  theme(legend.position = "right")+
  guides(fill=guide_legend(ncol=1,byrow=TRUE))
```

```{r}
# Plot Land Surface Temperature

# Convert LST from Kelvin to Calcius using scoff()
scoff(lst) <- cbind(0.02, -273.15)
plot(lst[[1:10]])
```

```{r}
lw <- data.frame(x= -78.791547,y=43.007211) %>%
  st_as_sf(coords=c("x","y"),crs = 4326)

st_transform (lw)
projection <- st_crs(st_transform (lw))

lst_data_extract<- extract(lst,lw,buffer=1000,fun=mean,na.rm=T)

lst_data_extract[1] <- NULL
Vertical_lst_data_extract <- t(lst_data_extract)
dates <- time(lst)

c_dates_lst <- data.frame(dates,Vertical_lst_data_extract)
```

```{r}
ggplot(data = c_dates_lst, aes(x = dates, y = Vertical_lst_data_extract))+
  geom_point()+
  geom_smooth(span = 0.045, n = 881)+
  ylab("Monthly Mean Land Surface Temperature")+
  xlab("Date")+
  labs(title = "Monthly Mean Land Surface Temperature Over Time")
```

```{r}
# Summerize weekly data to monthly climatologies
lst_month <- tapp(x = lst,index = 'month', fun = "mean", na.rm = TRUE)

#Layer names to Month names
names(lst_month)=month.name[as.numeric(str_replace(names(lst_month),"m_",""))]
```

```{r}
gplot(lst_month)+
  geom_raster (aes(fill = value))+
  facet_wrap (~variable, ncol = 3)+
  scale_fill_gradient2 ()+
  theme_bw()+
  theme( axis.title = element_blank(), axis.text = element_blank())
```
```{r}
monthly_means <- global(lst_month, mean, na.rm = TRUE)
kable(monthly_means,col.names = "Mean", align = "cc")
```
```{r}
lulc2 <- resample(lulc, lst, method = "near")
lcds1 <- cbind.data.frame(
  values (lst_month),
  ID = values (lulc2[[1]])) %>%
  na.omit()

lcds2 <- lcds1 %>%
gather(key="month", value = "value", -Land_Cover_Type_1_1) %>%
mutate(ID = as.numeric (Land_Cover_Type_1_1)) %>%
mutate(month = factor (month ,levels = month.name, ordered = TRUE)) %>%
left_join(land_cover_data) %>%
filter(landcover%in%c("Urban & built-up","Deciduous Broadleaf forest"))
```

```{r}
ggplot(lcds2, aes (x = month, y = value))+
geom_jitter(alpha = .5) +
geom_violin(scale = "width", position = "dodge", color = "red", fill = "green", alpha = 0.5)+
xlab ("Month")+
ylab ("Monthly Mean Land Surface temoerature (C)")+
labs(title = "Land Surface Temperature in Urban and Forest")+
facet_wrap (~landcover)
```
